### ISSUE TITLE
Getting bunch of errors when I try to open the Manager, no idea what are those

### ISSUE THREAD

**Issue by YashPatole** [gw2-addon-loader/GW2-Addon-Manager#125]
I downloaded the software, but I did had a addon before which was mount radial but I deleted the dxd9.dll file before installing the Addon Manager, after installing it on same drive with guild wars 2 its not running, I tried to run it as administrator still the issues are showing up..... I can't really tell more about it in technical way, so I'm gonna attach the pics
![error1](https://user-images.githubusercontent.com/77581975/132696112-1de4a740-b914-4d74-badd-a38d1deaacfc.png)
![error2](https://user-images.githubusercontent.com/77581975/132696124-67824171-6d07-4f65-96fb-97516be156f9.png)
![error3](https://user-images.githubusercontent.com/77581975/132696133-e7f6c639-a832-4119-bbb8-83e58a78dfd6.png)

**Comment by ALERTua** [comment]
same here
![image](https://user-images.githubusercontent.com/8375129/133209795-dbb96d2c-aa71-4df1-b426-60c00576088b.png)

**Comment by wylel** [comment]
Yeah I actually just updated to 1.3.0.3 and this is happening to me now as well.

**Comment by jlvantrease** [comment]
I am gettig the same error message

**Comment by hackmoore** [comment]
Same issue

**Comment by IanBFarrell** [comment]
same here

**Comment by IanBFarrell** [comment]
I deleted everything out of the addon folder and the d3d files. Then I redownloaded and tried and it worked. My issue is now I get in the app but menu commands for the addons are not working. Does anyone know what I can do?

**Comment by nicodemus4802** [comment]
I haven't had the same luck as @IanBFarrell after deleting and re-downloading, but here's the latest log entry:


```[Log Entry]
9/24/2021 9/24/2021 21:55:47
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\Backend\Addons\ApprovedList.cs:line 34
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\Backend\Addons\ApprovedList.cs:line 86
   at GW2_Addon_Manager.OpeningViewModel..ctor() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\UI\OpeningPage\OpeningViewModel.cs:line 222
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\UI\OpeningPage\OpeningViewModel.cs:line 237
   at GW2_Addon_Manager.OpeningView..ctor() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\UI\OpeningPage\OpeningView.xaml.cs:line 31```

**Comment by IanBFarrell** [comment]
Thanks, I used the Clean and Install option and that seemed to fix it. Finally back up and running.

**Comment by Friendly0Fire** [comment]
These issues are due to hitting rate limits on the Github API. Your only option is to wait around an hour to be allotted extra calls, or to switch IPs (e.g. through a VPN).

I am working on fixing this problem and tracking it in issue #134.
