### ISSUE TITLE
Bugs in v1.4.0

### ISSUE THREAD

**Issue by accelleratii** [gw2-addon-loader/GW2-Addon-Manager#142]
Downloaded package.zip from Addon Manager v1.4.0 alpha and placed contents in a folder on same drive as the game.

Launched the GW2 Addon Manager.exe

- With no addon ticked pressing "Update" gives error: "Unable to locate Guild Wars 2 /bin/ or /bin64/ folder. Please verify Game Path is correct." (path is correct).

"Reset to Clean Install" from "Configuration Options" removes the error.

- Selecting any addons and re-enabling does not seem to have effect, they stay unticked on app re-launch. Although files: d3d11.dll; dxgi.dll; addonLoader.dll were created in Guild Wars 2 folder and file d3d9.dll was created in Guild Wars 2\bin46 folder.

On the top (title bar) app shows: "v1.4.1 available!" and an "Update" button alongside.

- Pressing Update fills the red bar stating "Download complete!" this resets and repeats at app re-launch.

**Comment by accelleratii** [comment]
App stopped launching after few more tests, Event Viewer:

**Error: Application Error**

Faulting application name: GW2 Addon Manager.exe, version: 1.0.0.0, time stamp: 0xa226d9bd
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1202, time stamp: 0x448a4f5d
Exception code: 0xe0434352
Fault offset: 0x0012b5b2
Faulting process id: 0x2630
Faulting application start time: 0x01d7b4409297d1cd
Faulting application path: C:\Games\gw2am\GW2 Addon Manager.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 343ea0a5-639e-43d5-ab16-a7c63b9c26cf
Faulting package full name: 
Faulting package-relative application ID: 

**Error: .NET Runtime**

Application: GW2 Addon Manager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
   at System.Net.WebClient.DownloadString(System.Uri)
   at System.Net.WebClient.DownloadString(System.String)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(System.IO.Stream, System.Uri, Boolean, Boolean, Boolean, Boolean, System.Windows.Markup.XamlReader ByRef)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(System.IO.Stream, MS.Internal.ContentType, System.Uri, Boolean, Boolean, Boolean, Boolean, System.Windows.Markup.XamlReader ByRef)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(System.Net.WebRequest, System.Net.WebResponse, System.Uri, System.Object)
   at System.Windows.Navigation.NavigationService.DoNavigate(System.Uri, System.Windows.Navigation.NavigationMode, System.Object)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at System.Windows.Application.Run()
   at GW2_Addon_Manager.App.App.Main()

**Comment by lcharrie** [comment]
Pretty much the same constatations here.
- Fresh install of the v1.4.1.
- When I launch addons-manager, it says "v1.4.1 available!". The update button download the version in "latest-version" dir, but fails to unpack (file not found).
- If I unpack it manually, the updated addon-manager still says "v1.4.1 available!".

I then add only Radial and start GW2. Nothing happens.
```
[WARN] core | Addon "gw2radial" is not loaded due to wrong dependency version "loader_core". Require v0.1(r1) but have v1.0(r33)
[ERR] core | addons/gw2radial/gw2addon_gw2radial.dll dependency outdated
```

So loader-core version in v1.4.1 addons-manager is not updated to v1.0, and I don't know how to do it manualy.

**Comment by gShadw** [comment]
This 1.4.1 have not good version info :

[INFO] core | Addon loader v1.0 (v1.1 r33) initialized   

Fresh Install + only ArcDps :

[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r401
[INFO] core | Loading d3d9_wrapper
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system d3d9
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[WARN] core | Init called twice without proper unload. If your addon is not working, make sure you handle this situation!
[INFO] d3d9_wrapper | Loading system dxgi
[INFO] core | Unloading core addon
[ERR] core | Unloading addon arcdps failed with error 1
[ERR] core | Some addons are not unloaded!

Why post version not work with arcDps ? useless

**Comment by Atros04** [comment]
Installed 1.4.1 and got it to work first run. Any time after, I am being thrown an error. Log info below:

[Log Entry]
9/28/2021 9/28/2021 11:51:12 AM
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()
