### ISSUE TITLE
Unable to open the addon manager as of the latest release (v1.4.2)

### ISSUE THREAD

**Issue by BrentMifsud** [gw2-addon-loader/GW2-Addon-Manager#150]
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
After downloading the latest addon manager, I am unable to even open it. I am immediately greeted with a github error.

**To Reproduce**
Try to start Addon manager v1.4.2

**Additional context**
n/a

**don't forget to attach the config file to the issue**

Unable to attach a config file because it does not exist yet.

![image](https://user-images.githubusercontent.com/18543934/135367902-03ab0a9f-2dfe-4d2a-b37c-7d595d1ab2f5.png)

**Comment by Friendly0Fire** [comment]
I have no idea why Github's API is being this annoying, but I'm afraid the only way to solve this is to wait. I'm working on a new version of the manager that will fix this (among many other things), but it'll take time.

**Comment by BrentMifsud** [comment]
Strangely enough, if you download 1.4.1, then update to 1.4.2, this issue does not happen.

**Comment by ArchaeanDragon** [comment]
How can you update to 1.4.2? Running 1.4.1 has the same error, and there's no auto-updater in 1.4.1 anymore that I can see.

**Comment by BrentMifsud** [comment]
> How can you update to 1.4.2? Running 1.4.1 has the same error, and there's no auto-updater in 1.4.1 anymore that I can see.

There was an update button at the top of the window when I downloaded 1.4.1 🤷‍♂️

**Comment by ArchaeanDragon** [comment]
Yeah, I wasn't able to get to the main window, because it was throwing the github api error in 1.4.1 as well.
Seems to be working now, but when I try to update to 1.4.2, it says "download complete", then just sits there. If I try to close it it gives me another error "The system cannot find the file specified" and doesn't update.
Trying to manually update to 1.4.2 now.
Now GW2Radial is throwing a missing DLL procedure entry point error when I launch the game, but that's something for the GW2 Radial project. It seems to be working now, though.

**Comment by davidlukerice** [comment]
Had a similar issue in 1.4.2 after a fresh install (aka clear everything but gw2.exe and the .dat). Waiting  an hour didn't resolve it for me, but going back to1.4.1 worked.

**Comment by Arkkhalis64** [comment]
I get the same error message when I try to launch GW2-UOAOM v1.4.2 (clean install).
![GitHub-API-Error](https://user-images.githubusercontent.com/75038350/135397107-3ae0bb6c-88cb-4db3-a846-3f99249a7d69.png)

I get another error message when I click "OK" and the blank manager window in the background closes itself.
![Critical-Error-1](https://user-images.githubusercontent.com/75038350/135397234-0d07ddb6-469e-4545-a029-0a04c97b2679.png)

I get yet another error message when I click "OK".
If I click "OK" again with this message it repeats once then nothing happens if I click "OK" for the fourth time.
![Critical-Error-2](https://user-images.githubusercontent.com/75038350/135397513-17b7df9e-28dd-4dcd-a81c-1588a512efa5.png)

Despite having the same issue as the others, I do get a log file: [log.txt](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/7257186/log.txt)

**Comment by TagashiChiro** [comment]
Same issue with v1.4.2

And when I try v1.4.1, this happens...
![Screenshot 2021-09-30 182029](https://user-images.githubusercontent.com/91667259/135438448-c2492508-ed08-409a-8dd0-36a45c899ae0.png)
![Screenshot 2021-09-30 182109](https://user-images.githubusercontent.com/91667259/135438476-6eca7167-1917-4e81-a8d2-dd9b71e04d42.png)

**Comment by lcharrie** [comment]
I think there are  2 distincts problems there :
1) Yes, you'r sometimes hitting the GitHub API threshold with is realy low (60). To know if your IP hits the threshold you can ping https://api.github.com/rate_limit
2) But also, because of the refractoring you did on the WebClients in version 1.4.2, the function FetchListFromRepo is using the same WebClient object to fetch /branches and then /zipball, creating a race condition.
By calling UpdateHelpers.GetClient() again before the second api call, I'm able to start the manager.

**Comment by lcharrie** [comment]
@TagashiChiro 
> 
> And when I try v1.4.1, this happens... !

 `"Please verify Game Path is correct"`.
I can't see any game in the Guild Wars 2 folder you gave...

**Comment by ROMzombie** [comment]
Similar error, stacktrace from log:
```
9/30/2021 9/30/2021 11:32:03 AM
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Could not find file 'C:\Program Files\Guild Wars 2\Addon Manager\addonlist'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()
```
Ratelimit on the API looks like it should have tokens available: https://api.github.com/rate_limit
```
{"resources":{"core":{"limit":60,"remaining":21,"reset":1633029589,"used":39,"resource":"core"},"graphql":
{"limit":0,"remaining":0,"reset":1633030361,"used":0,"resource":"graphql"},"integration_manifest":
{"limit":5000,"remaining":5000,"reset":1633030361,"used":0,"resource":"integration_manifest"},"search":
{"limit":10,"remaining":10,"reset":1633026821,"used":0,"resource":"search"}},"rate":
{"limit":60,"remaining":21,"reset":1633029589,"used":39,"resource":"core"}}
```

**Comment by lalmanzar** [comment]
> Strangely enough, if you download 1.4.1, then update to 1.4.2, this issue does not happen. Seems to only happen on a fresh install of the addon manager

This workaround worked for me. Downloaded 1.4.1 and then updated. Issue was gone.

**Comment by williamboman** [comment]
The Update button didn't really do anything so I did a fresh manual installation and ran into the same issue as OP. I noticed my previous installation directory had a bunch of files that the new installation didn't have, so I just copied over those missing files and it started working for me 🤷‍♂️

**Comment by xivor** [comment]
I woke up today and tried to load up the AddonManager for the first time.
![image](https://user-images.githubusercontent.com/43550443/135615019-ba6dcf0c-9e88-4524-87d1-32b9b1fc4b34.png)

**Comment by xivor** [comment]
I can confirm that downloading 1.4.1, then using the update button at the top to download 1.4.2 does create a working installation.

**Comment by jopemoro** [comment]
Where can I find instructions on completely removing AddonManager and all the related dlls? 

1.4.1 and 1.4.2 give me errors and now even GW2 won't start... :(

**Comment by williamboman** [comment]
@jopemoro Try deleting the `addons` folder inside your GW2 installation? Might want to back it up if you want to attempt restoring any addon settings later

**Comment by jopemoro** [comment]
> @jopemoro Try deleting the `addons` folder inside your GW2 installation? Might want to back it up if you want to attempt restoring any addon settings later

Tx!! Ended up reinstalling GW2 and doing a manual install of GW2radial... I'll wait until Addonmanager works again :)
