### ISSUE TITLE
Add On Manager does not start; unable to access paths in its own directory

### ISSUE THREAD

**Issue by Zelbinian** [gw2-addon-loader/GW2-Addon-Manager#170]
![image](https://user-images.githubusercontent.com/4549706/146287292-24918bbc-be26-4b01-a45a-7ad4ac76cd2a.png)

**Describe the bug**
Fresh download, cannot open the program. Tried moving it around to various directories, running in administrative mode... no dice.

**Additional context**
Here is the content of the log:
[Log Entry]
12/15/2021 12/15/2021 12:49:18 AM
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Access to the path 'resources\addons\arcdps' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()

**don't forget to attach the config file to the issue**
^ I tried, GitHub said it didn't support the .config file type ¯\_(ツ)_/¯

**Comment by pjllorens** [comment]
Just happened to me. Solved it by deleting the folder "addons"

**Comment by Sonnass** [comment]
dont move the application file from its folder. Open it directly from the folder contents or right click-create shortcut to put it in the desktop
