### ISSUE TITLE
Is this project still alive? 

### ISSUE THREAD

**Issue by alhazmy13** [gw2-addon-loader/GW2-Addon-Manager#196]
There's a lot of issues and PR still opened for this project, the latest build released like 10 months ago, is there anyone working on fork to solve these issues?

**Comment by SatyricL** [comment]
Doesn't seem like it. The 403 error issue has gone from an issue that you can get around by running as admin, to an issue that happens every time regardless. The mod manager is now 100% unusable for me. Hope its resolved at some point. Going to have to rely on manually installing addons for the foreseeable future.

**Comment by Friendly0Fire** [comment]
A 403 error means you need to stop and wait, it has absolutely nothing to do with running as admin.

**Comment by SatyricL** [comment]
> A 403 error means you need to stop and wait, it has absolutely nothing to do with running as admin.

I read in passed posts that it happens when you try to open the manager too many times. However, it occured the first time I opened the manager in 2 months. Before you could get passed this issue by running the manager in admin mode. Now it happens every time, regardless of running in admit, first time every time, and no longer how long you wait.

I posted a bug report highlighting that it was not a waiting issue, but it was deleted because it was too close to someone else who posted a year ago about the 403 error.

**Comment by Friendly0Fire** [comment]
You can think or claim whatever you want, we don't make up the error code, we pass it along from Github. Github doesn't care about you running as admin, it can't even know that, and if it says you've hit the Github API too many times, it'll block you. Nothing we can do about it other than to tell people to wait, since the primary reason for a 403 is that the manager was opened too often/recently.

**Comment by SatyricL** [comment]
> You can think or claim whatever you want

I could say the same to you. I'm not posting to argue with you, and I am not implying you made anything up. I am simply informing you that the error is being given to some people despite opening the program for the first time. And despite it not making sense, running in admit was bypassing this issue. The last two patches of the game gave me Error 403 on the very first opening. The first occurrence, after not being able to figure it out, I was told to try running in admin mode. I did, and it worked. The next patch, I opened the AOM for the first time since, and again, Error 403. Admin mode immediately bypassed it. Now 403 error occurs first time upon opening as usual, only admin mode no longer fixes it.

Whether or not the admin mode bypass is a placebo fix or not, the 403 error occurring on the first start up is very real. Whether its an issue with the AOM or with github itself, I am sure you know better then me. Just stating that it is happening, and its currently rendered the AOM unusable for some.

**Comment by theLockesmith** [comment]
Arguments aside, is the project still being maintained?

**Comment by BenKennish** [comment]
*bump*

I'm having problems with using arcdps using GW2UAOM, I don't know whether GW2UAOM is to blame but idk whether to continue use of this tool if it's not maintained anymore.

**Comment by bluenote73** [comment]
Clearly 403 can happen on first open.

**Comment by BenKennish** [comment]
Ok so assuming the answer to the question in the title of this issue is "no", possibly a safe assumption given that the issue was posted just under 4 months ago with no response from any of the developers, does anyone know of any alternatives to GW2UAOM?

**Comment by Areos-Hotah** [comment]
> Clearly 403 can happen on actual first open. What the user should do when they encounter this is wait and try again. Personally I've had it work ~10 or so minutes later but YMMV and longer is better I'm sure. To cut down on these complaints this should probably be on the main page.

Ok tried once, ran it normal. Waited 10 minutes.  Tried running as Admin, failed, here is the error:

[Log Entry]
12/5/2022 12/5/2022 10:06:55 AM
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Unable to connect to the remote server
   at GW2_Addon_Manager.UpdateHelpers.DownloadStringFromGithubAPI(WebClient wc, String url)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()
An attempt was made to access a socket in a way forbidden by its access permissions 20.205.243.168:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
[Log Entry]
12/5/2022 12/5/2022 10:32:30 AM
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Unable to connect to the remote server
   at GW2_Addon_Manager.UpdateHelpers.DownloadStringFromGithubAPI(WebClient wc, String url)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()
An attempt was made to access a socket in a way forbidden by its access permissions 20.205.243.168:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

**Comment by theLockesmith** [comment]
> > Clearly 403 can happen on actual first open. What the user should do when they encounter this is wait and try again. Personally I've had it work ~10 or so minutes later but YMMV and longer is better I'm sure. To cut down on these complaints this should probably be on the main page.
> 
> Ok tried once, ran it normal, failed. Waited 10 minutes. Tried running as Admin, failed again, here is the error:
> 
> [Log Entry] 12/5/2022 12/5/2022 10:06:55 AM The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception. at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri) at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream) at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc) at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter) at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter) at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState) at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState) at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) Unable to connect to the remote server at GW2_Addon_Manager.UpdateHelpers.DownloadStringFromGithubAPI(WebClient wc, String url) at GW2_Addon_Manager.ApprovedList.FetchListFromRepo() at GW2_Addon_Manager.ApprovedList.GenerateAddonList() at GW2_Addon_Manager.OpeningViewModel..ctor() at GW2_Addon_Manager.OpeningViewModel.get_GetInstance() at GW2_Addon_Manager.OpeningView..ctor() An attempt was made to access a socket in a way forbidden by its access permissions 20.205.243.168:443 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) [Log Entry] 12/5/2022 12/5/2022 10:32:30 AM The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception. at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri) at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream) at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc) at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter) at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter) at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState) at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState) at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) Unable to connect to the remote server at GW2_Addon_Manager.UpdateHelpers.DownloadStringFromGithubAPI(WebClient wc, String url) at GW2_Addon_Manager.ApprovedList.FetchListFromRepo() at GW2_Addon_Manager.ApprovedList.GenerateAddonList() at GW2_Addon_Manager.OpeningViewModel..ctor() at GW2_Addon_Manager.OpeningViewModel.get_GetInstance() at GW2_Addon_Manager.OpeningView..ctor() An attempt was made to access a socket in a way forbidden by its access permissions 20.205.243.168:443 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

This appears to be a limitation of github that is then (possibly) combined with how the application is trying to reach github. The only way I've found to fix this is to use a vpn when I get this error.

**Comment by theLockesmith** [comment]
@Friendly0Fire I see you added the `help wanted` tag, what kind of help are you looking for? Is this project still maintained or should someone consider forking it and picking it up?

**Comment by Friendly0Fire** [comment]
Someone is needed to carry the redesign to the finish line, essentially. It's already in large parts complete, but the transition to a stateless system was never finished.

I would not recommend forking due to the interconnected nature of the app and its various projects. PRs are welcome.

**Comment by adamk33n3r** [comment]
I've been getting this issue every single launch when trying to launch from the start menu. But if I try to launch the exe directly from the directory I extracted it from, it works fine. What would cause launching from the start menu to break it like this?

**Comment by JinxLuckless** [comment]
> Someone is needed to carry the redesign to the finish line, essentially. It's already in large parts complete, but the transition to a stateless system was never finished.
> 
> I would not recommend forking due to the interconnected nature of the app and its various projects. PRs are welcome.

If someone is willing to take the time to show me how to update just which mod files it's calling to (as a PR), I would be happy to update it at least this time, and I'll try to write up the notes I take for others to do the same, so it could be updated more often.

I'm pretty sure the crash issue I'm having right now is due to it calling for an older arcdps version (or an older version of arcdps-related addons). I've not really done PRs before, but I think I could handle this.

**Comment by megmeyxxx** [comment]
hey i must ask someone
maybe polish version translate? this is immportant to me

**Comment by Prodigio** [comment]
@Friendly0Fire I did some work on the redesign on my fork. Some minor things are to be done, yet. But it seems to work so far.

Are there any open points I should have a look on?

Maybe you can have a look?

**Comment by greaka** [comment]
2000 lines of formatting are hard to read. Next time please split out formatting and actual changes into separate commits.
