### ISSUE TITLE
Game crashes after installation

### ISSUE THREAD

**Issue by master1782** [gw2-addon-loader/GW2-Addon-Manager#201]
After installing arcdps via the Addon Manager, the game no longer starts.
Uninstalling via the Addon Manager does not work either. I get the following error code

[Log Entry]
2/19/2023 2/19/2023 10:08:55 AM
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
The remote server returned an error: (403) Forbidden.
   at GW2_Addon_Manager.UpdateHelpers.DownloadStringFromGithubAPI(WebClient wc, String url)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()

Since my English is not very good I don't understand what has to be done.

**Comment by Luso0** [comment]
This project is old and hasn't been updated since Oct 1st, 2021 (Version 1.4.3) at the time of this writing. It seems to be downloading the 2021-09-27 version of the files and that is what is causing the crash.

Delete these files:
C:\Program Files\Guild Wars 2\d3d11.dll
C:\Program Files\Guild Wars 2\dxgi.dll
C:\Program Files\Guild Wars 2\addonLoader.dll
C:\Program Files\Guild Wars 2\bin64\d3d9.dll

Download the latest arcdps https://www.deltaconnected.com/arcdps/x64/ and place it in C:\Program Files\Guild Wars 2\d3d11.dll for now. Honestly would stop using this Addon Manager unless it gets a functional update.
